steps:

- name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'build'
    - '-t' 
    - '${_REPO_REGION}/${_GLOBAL_ARTIFACT}/${_REPO_NAME}/${_SERVICE_NAME}'
    - '--build-arg=REACT_APP_API_URL=${_REACT_APP_API_URL}'
    - '--build-arg=REACT_APP_SECRET_KEY=${_REACT_APP_SECRET_KEY}'
    - '.'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REPO_REGION}/${_GLOBAL_ARTIFACT}/${_REPO_NAME}/${_SERVICE_NAME}']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - '${_SERVICE_NAME}'
  - '--image=${_REPO_REGION}/${_GLOBAL_ARTIFACT}/${_REPO_NAME}/${_SERVICE_NAME}'
  - '--port=80'
  - '--region=${_REGION}'
  - '--platform=managed'
  - '--allow-unauthenticated'
  - '--service-account=${_SERVICE_ACCOUNT}'
  - '--max-instances=5'
  - '--timeout=3600'
  - '--memory=1024Mi'

images:
- ${_REPO_REGION}/${_GLOBAL_ARTIFACT}/${_REPO_NAME}/${_SERVICE_NAME}

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REPO_REGION: us-docker.pkg.dev
  _REPO_NAME: pa-dev-repo
  _SERVICE_NAME: pa-dev-web
  _REGION: us-central1
  _PROJ_ID: np-pa-dev
  _GLOBAL_ARTIFACT: glb-pa-artifactory
  _SERVICE_ACCOUNT: sa-np-pa-dev@np-pa-dev.iam.gserviceaccount.com
  _REACT_APP_API_URL: 'https://pa-dev-api.thesynapses.com'
  _REACT_APP_SECRET_KEY: '8354190646727484'
