const LibraryPage = () => {
  return (
    <div className="h-full overflow-y-auto">
      <div className="max-w-[892px] px-5 mx-auto">
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
        <h3>Library</h3>
      </div>
    </div>
  );
};

export default LibraryPage;
